name: Apply Tag

on:
  push:
    branches:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set version from branch name
        id: set_version
        run: |
          version=$(echo "${{ github.ref }}" | sed 's/refs\/heads\/release\///')
          echo "version=$version" >> $GITHUB_OUTPUT
          
      - name: Set project version
        run: |
          sed -i "s/<Version>.*<\/Version>/<Version>${{ steps.set_version.outputs.version }}<\/Version>/" VRLabs.VRCTools.Packaging/VRLabs.VRCTools.Packaging.csproj
          sed -i "s/<Version>.*<\/Version>/<Version>${{ steps.set_version.outputs.version }}<\/Version>/" VRLabs.VRCTools.Packaging.Console/VRLabs.VRCTools.Packaging.Console.csproj

      - name: Configure git
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          git config --global user.password '${{ secrets.GITHUB_TOKEN }}'

      - name: Commit version change
        run: |
          git add .
          git commit -m "Bump version to ${{ steps.set_version.outputs.version }}"

      - name: Apply tag to commit
        run: |
          git tag -a ${{ steps.vars.set_version.version }} -m "Version ${{ steps.vars.set_version.version }}"
          git push --tags